# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Built From Here"
description:	       "Stories of the builders from places less populated."
author:              "Justin Lewis"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# mapping:
#     provider: openstreetmap-leaflet
#     # api_key: AIzaSyDNhj22EqZoDYXSF90FMCQjS-nQx4JG4uI
#     zoom: 10
#     dimensions:
#         width: 600
#         height: 400

leaflet: "leaflet@1.0.2"
